### ISSUE TITLE
Method to pass a QueryBase to CDSDataComboBox

### ISSUE THREAD

**Issue by rappen** [jamesnovak/xrmtb.XrmToolBox.Controls#5]
Since CDSDataComboBox has a service, it would be pretty nice if you could just pass a query to the control and it would perform all the loading itself.

Interaction with the UI in the form of the XrmToolBox specific "yellow progress panel" might be tricky to implement nicely, perhaps @jamesnovak has some input here.

**Comment by jamesnovak** [comment]
the internal loading of data should not be a big deal.  add a method that takes fetch or a query expression.  same is done with some other controls. 
but displaying the loader message would mean a dependency on the XrmToolBox.  I've tried wrapping up the load/set datasource methods in the WorkAsync and raising events but it crashes because of threading issues.

**Comment by jamesnovak** [comment]
well, there IS a method to show the control!

var infoPanel = InformationPanel.GetInformationPanel(this, "Loading Stuff", 340, 150);
infoPanel.BringToFront();
Refresh();

and when done - 

if (this.Controls.Contains(infoPanel)) {
    infoPanel.Dispose();
    Controls.Remove(infoPanel);
}

**Comment by rappen** [comment]
Interesting.... 
I was thinking more along the lines of
`myGridView.RetrieveMultiple(query, progresshandler, callback);`

That would still keep it without dependency on XTB, I think...
